choices/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('choices.views',
    url(r'^create_choice/$', 'create_choice'),
    url(r'^submitted/$', 'submitted'),
    url(r'^view_ultimatums/$', 'view_ultimatums'),
    url(r'^view_ultimatum/(?P<id>[0-9]+)$', 'view_ultimatum'),
)

ultimatum/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^choices/', include('choices.urls')),
    (r'^users/', include('users.urls')),
    (r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('ultimatum.views',
    # index.html is often used as default homepage address
    # and every sub address, e.g. events/index.html
    # TODO: need to update!
    url('^$', 'splash'),
    url(r'^welcome/$', 'welcome'),
    url(r'^home/$', 'home'),
    url(r'^accounts/login/$', 'login'),
    url(r'^accounts/logout/$', 'logout'),
    url(r'^accounts/loggedin/$', 'home', {"message": "Welcome User, you are now logged in."}),
    url(r'^accounts/register/$', 'register_user'),
    url(r'^accounts/register_success/$', 'home', {"message": "Welcome User, your registration was successful."}),
)

users/urls.py
from django.conf.urls import patterns, include, url
import users


urlpatterns = patterns('users.views',
    url(r'^update_friends/$', 'update_friends'),
)

choices/models.py
from django.db import models
from django.utils import timezone

from users.models import SiteUser



class ActiveManager(models.Manager):
    def get_query_set(self):
        return super(ActiveManager, self).get_query_set().filter(expired=False)

class ExpiredManager(models.Manager):
    def get_query_set(self):
        return super(ExpiredManager, self).get_query_set().filter(expired=True)

class Choice(models.Model):
    
    TIME_LIMIT_CHOICES = (
    (10, '10 minutes'),
    (30, '30 minutes'),
    (60, '1 hour'),
    (360, '6 hours'))

    SHARE_WITH_CHOICES = (
    ('some', 'Select few'),
    ('all', 'All friends'),
    ('public', 'Public')) 

    question = models.CharField(max_length=300, blank=False)
    image1 = models.ImageField(blank=True, upload_to="images/uploaded_images/")
    image2 = models.ImageField(blank=True, upload_to="images/uploaded_images/")
    text1 = models.TextField(max_length=200, blank=True)
    text2 = models.TextField(max_length=200, blank=True)
    url1 = models.URLField(max_length=200, blank=True)
    url2 = models.URLField(max_length=200, blank=True)
    time_created = models.DateTimeField(default=timezone.now())
    time_limit = models.IntegerField(choices=TIME_LIMIT_CHOICES, default=60)
    share_with = models.CharField(max_length=200, choices=SHARE_WITH_CHOICES, default='all')
    # info on related_name: http://stackoverflow.com/questions/2642613/what-is-related-name-used-for-in-django
    share_list = models.ManyToManyField(SiteUser, related_name="choice_shared_list", blank=True)
    voted_1 = models.ManyToManyField(SiteUser, related_name="choice_voted_1")
    voted_2 = models.ManyToManyField(SiteUser, related_name="choice_voted_2")
    created_by = models.ForeignKey(SiteUser, related_name="creator")
    accepted = models.CharField(max_length=10, blank=True)
    objects = models.Manager() # default Manager
    active_set = ActiveManager()
    expired_set = ExpiredManager()

    @property
    def time_remaining(self):
        time_delta_since_created = timezone.now() - self.time_created
        time_delta_in_mins = time_delta_since_created.seconds/60
        return self.time_limit - time_delta_in_mins

    @property
    def time_remaining_str(self):
        time_delta_since_created = timezone.now() - self.time_created
        time_delta_in_mins = time_delta_since_created.seconds/60
        time_remaining = self.time_limit - time_delta_in_mins
        if time_remaining > 120:
            return "{} hours {} minutes".format(str(time_remaining // 60), str(time_remaining % 60))
        elif time_remaining > 60:
            return "{} hour {} minutes".format(str(time_remaining // 60), (time_remaining % 60))
        else:
            return "{} minutes".format(str(time_remaining))

    @property
    def expired(self):
        if self.time_remaining < 0:
            return True
        return False

    @property
    def total_votes(self):
        return len(self.voted_1.all()) + len(self.voted_2.all())

    class Meta:
        ordering = ('time_created',)

    def __unicode__(self):
        return self.question
 

class Comment(models.Model):
    user = models.ForeignKey(SiteUser)
    choice = models.ForeignKey(Choice)
    content = models.TextField(max_length=200)
    time_created = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        if len(self.content) > 10:
            return self.content[:10]
        return  self.content

choices/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from choices.models import Choice, Comment


class ChoiceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ChoiceForm, self).__init__(*args, **kwargs)
        if user:
            print "User friends:", user.friends.all()
            self.fields['share_list'].queryset = user.friends.all() 

    class Meta:
        model = Choice
        fields = ['question', 'image1', 'image2', 'text1', 'text2', 'url1', 'url2', 
                  'time_limit', 'share_with', 'share_list']
        widgets = {
            'share_list': forms.CheckboxSelectMultiple(),
        }
        labels = {
            'question': _('Question'),
            'image1': _('Image'),
            'text1': _('Text'),
            'url1': _('URL'),
            'image2': _('Image'),
            'text2': _('Text'),
            'url2': _('URL'),
            'time_limit': _('Time limit'),
            'share_with': _('Share with'),
        }

    def clean(self, *args, **kwargs):
        super(ChoiceForm, self).clean(*args, **kwargs)
        image1 = self.cleaned_data["image1"]
        text1 = self.cleaned_data["text1"]
        url1 = self.cleaned_data["url1"]

        if not (image1 or text1 or url1):
            raise forms.ValidationError("Please enter something for Option A")

        image2 = self.cleaned_data.get("image2")
        text2 = self.cleaned_data.get("text2")
        url2 = self.cleaned_data.get("url2")

        if not (image2 or text2 or url2):
            raise forms.ValidationError("Please enter something for Option B")

        if self.cleaned_data["share_with"] == "public":
            self.cleaned_data["share_list"] == []
        return self.cleaned_data

class VoteForm(forms.Form):
    vote = forms.ChoiceField(choices=((1, "Option A"), (2, "Option B")))


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows':2, 'cols':20}),
        }

class AcceptedForm(forms.Form):
    accepted = forms.ChoiceField(choices=(("A", "Option A"), ("B", "Option B")))

choices/views.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.db.models import F, Q
from django.http import Http404, HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import Context
from django.template.loader import get_template

from choices.models import Choice, Comment
from choices.forms import ChoiceForm, VoteForm, CommentForm, AcceptedForm


@login_required
def create_choice(request):
    args = {}
    this_user = request.user.siteuser
    if request.method == 'POST':
        form = ChoiceForm(request.POST, request.FILES)
        if form.is_valid():
            choice = form.save(commit=False)
            choice.created_by = this_user
            choice.time_created = timezone.now()
            choice.save()
            # m2m needs to be saved manually after a partial save of instance:
            # https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#the-save-method
            form.save_m2m()
            return HttpResponseRedirect('/choices/submitted/')
        else:
            args['form'] = form
    else:
        args['form'] = ChoiceForm(user=this_user, initial={"share_list": this_user.friends.all()})
    args.update(csrf(request))
    return render_to_response('choices/create_choice.html', args)


@login_required
def submitted(request):
    args = {'choice':Choice.objects.filter(created_by=request.user).reverse()[0]}
    return render_to_response('choices/submitted_choice.html', args)


@login_required
def view_ultimatums(request):
    args = {}
    this_user = request.user.siteuser
    args['user_ultimatums'] = sorted(Choice.objects.filter(created_by=this_user), key=sort)
    args['other_ultimatums'] = sorted(Choice.objects.filter(share_list=this_user).exclude(created_by=this_user).exclude(share_with="public"), key=sort)
    args['public_ultimatums'] = sorted(Choice.objects.filter(share_with="public").exclude(created_by=this_user), key=sort)
    args['siteuser'] = this_user
    return render_to_response('choices/view_ultimatums.html', args)


def sort(m):
    if m.time_remaining < 0:
        return 100000
    return m.time_remaining


@login_required
def view_ultimatum(request, id=None):
    args = {}
    this_user = request.user.siteuser
    this_choice = get_object_or_404(Choice, pk=id)
    args['siteuser'] = this_user
    args['choice'] = this_choice

    if (request.method == 'POST' and this_user not in this_choice.voted_1.all()
        and this_user not in this_choice.voted_2.all() and this_choice.created_by != this_user):
        form = VoteForm(request.POST)
        form2 = CommentForm(request.POST)
        if form.is_valid():
            vote = int(form.cleaned_data['vote'])
            if vote==1:
                this_choice.voted_1.add(this_user)
            elif vote==2:
                this_choice.voted_2.add(this_user)
            this_choice.save()
            if form2.is_valid():
                content = form2.cleaned_data['content']
                if content:
                    Comment.objects.create(user=this_user, choice=this_choice, content=content) 
            args["message"] = "Thank you for voting."
            return render_to_response('choices/view_ultimatum.html', args)

    if this_choice.expired:
        args['votes_1'] = len(this_choice.voted_1.all())
        args['votes_2'] = len(this_choice.voted_2.all())
        args['total_votes'] = this_choice.total_votes
        args['commentsA'] = this_choice.comment_set.filter(choice__voted_1 = F('user'))
        args['commentsB'] = this_choice.comment_set.filter(choice__voted_2 = F('user'))
        this_user.viewed_results.add(this_choice)
        if this_choice.created_by == this_user and not this_choice.accepted:
            if request.method == 'POST':
                form = AcceptedForm(request.POST)
                if form.is_valid():
                    this_choice.accepted = form.cleaned_data['accepted']
                    this_choice.save()
            else:
                args['form3'] = AcceptedForm()
                args.update(csrf(request))
        return render_to_response('choices/view_ultimatum_results.html', args)

    if not (this_choice.created_by==this_user):
        this_user.viewed_current.add(this_choice)
        if (this_user in this_choice.share_list.all()):
            if (this_user not in this_choice.voted_1.all() and 
                this_user not in this_choice.voted_2.all()):
                args['form'] = VoteForm()
                args['form2'] = CommentForm()
                args.update(csrf(request))
                args["message"] = "You have not yet voted."
            else:
                args["message"] = "You have already voted"
    
    else:
        args["message"] = "Please come back later to review the results of your question."


    args.update(csrf(request))
    return render_to_response('choices/view_ultimatum.html', args)

templates/choices/create_choice.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load template_library %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "assets/css/create_choice.css" %}"/>
{% endblock %}

{% block title %}
Create Choice
{% endblock %}

{% block body_title %}
Create your choice
{% endblock %}

{% block content %}
<form id = 'choice_form' action="/choices/create_choice/" method="post" enctype='multipart/form-data'>{% csrf_token %}

    <div class="row" id="question_container">
        {% if form.non_field_errors %}{{ form.non_field_errors }}<br />{% endif %}
        {% if form.question.errors %}{{ form.question.errors }}{% endif %}
        {{ form.question.label }}:{{ form.question }}
    </div> <!--row-->
    <hr />

    <div class="row" id="option_container">
        <div class="col-md-1"></div>
        <div class="col-md-4" id="option1">
        Option A:
        <div id="format_buttons1">
            Format: 
            <button type="button" id="image1_button">Image</button>
            <button type="button" id="text1_button">Text</button> 
            <button type="button" id="url1_button">URL</button>
        </div>
        <div id="image1" class="upload_field">
            {% if form.image1.errors %}{{ form.image1.errors }}<br />{% endif %}
            {{ form.image1.label }}:{{ form.image1 }} <br />
        </div>
        <div id="text1" class="upload_field">
            {% if form.text1.errors %}{{ form.text1.errors }}<br />{% endif %}
            {{ form.text1.label }}:{{ form.text1 }} <br />
        </div>
        <div id="url1" class="upload_field">
            {% if form.url1.errors %}{{ form.url1.errors }}<br />{% endif %}
            {{ form.url1.label }}:{{ form.url1 }}
        </div>
        </div> <!--option container-->
        <div class="col-md-2"></div>
        <div class="col-md-4" id="option2">
        Option B:
        <div id="format_buttons2">
            <button type="button" id="image2_button">Image</button>
            <button type="button" id="text2_button">Text</button>
            <button type="button" id="url2_button">URL</button>
        </div>
        <div id="image2" class="upload_field">
            {% if form.image2.errors %}{{ form.image2.errors }}<br />{% endif %}
            {{ form.image2.label }}:{{ form.image2 }} <br />
        </div>
        <div id="text2" class="upload_field">
            {% if form.text2.errors %}{{ form.text2.errors }}<br />{% endif %}
            {{ form.text2.label }}:{{ form.text2 }} <br />
        </div>
        <div id="url2" class="upload_field">
            {% if form.url2.errors %}{{ form.url2.errors }}<br />{% endif %}
            {{ form.url2.label }}:{{ form.url2 }}
        </div>
        </div><!--option2 container-->
        <div class="col-md-1"></div>
    </div> <!--row-->

    <div class="row" id="time_container">
        <div class="col-md-3"></div>
        <div class="col-md-6" id="timer">
            {% if form.time_limit.errors %}{{ form.time_limit.errors }}{% endif %}
            {{ form.time_limit.label }}:{{ form.time_limit }}
        </div>
        <div class="col-md-3"></div>
    </div> <!--row-->

    <div class="row" id="share_with_container">
        <div class="col-md-3"></div>
        <div class="col-md-6" id="share_with">
            {% if form.share_with.errors %}{{ form.share_with.errors }}{% endif %}
            {{ form.share_with.label }}:{{ form.share_with }}
        </div>
        <div class="col-md-3"></div>
    </div> <!--row-->

    <div class="row" id="share_list_container">
        <div class="col-md-3"></div>
        <div class="col-md-6" id="share_list">
            {% if form.share_list.errors %}{{ form.share_list.errors }}{% endif %}
            {{ form.share_list }}
        </div>
        <div class="col-md-3"></div>
    </div> <!--row-->

    <input type='submit' value='submit' id='submit'/>
</form>
{% endblock %}

{% block footer %}
<p style="text-align: center">Click <a href='/accounts/logout/'>here</a> to logout.</p>
{% endblock %}


{% block scripts %}
<script id="format_display">
$('#image1_button').click(function() {
    $('#image1').toggle(200)
});
$('#text1_button').click(function() {
    $('#text1').toggle(200)
});
$('#url1_button').click(function() {
    $('#url1').toggle(200)
});
$('#image2_button').click(function() {
    $('#image2').toggle(200)
});
$('#text2_button').click(function() {
    $('#text2').toggle(200)
});
$('#url2_button').click(function() {
    $('#url2').toggle(200)
});

</script>

<script id="show_friends">
/* Shows friend list if user selects that they only want to share with some*/
$('#id_share_with').click(function() {
    if($(this).val()=="some") {
        $('#share_list').css("display", "block");
    }
})
</script>
{% endblock %}

templates/choices/submitted_choice.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load template_library %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "assets/css/view_ultimatum.css" %}"/>
{% endblock %}

{% block title %}
View Choice
{% endblock %}

{% block body_title %}
View your choice
{% endblock %}

{% block content %}

Your choice was submitted.
<div class="row" id="question_container">
    Your question: {{ choice.question }}
</div>
<hr/>

<div class="row" id="option_container">
    <div class="col-md-1"></div>
     <div class="col-md-4" id="option1">
        Option A <br />
        {% if choice.image1 %}
            <img src='/static/assets/{{ choice.image1 }}'/><br />
        {% endif %}
        {% if choice.text1 %}
            {{ choice.text1 }}<br />
        {% endif %}
        {% if choice.url1 %}
            <a href="{{ choice.url1 }}">{{ choice.url1 }}</a>
        {% endif %}
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4" id="option2">
        Option B <br />
        {% if choice.image2 %}
            <img src='/static/assets/{{ choice.image2 }}'/><br />
        {% endif %}
        {% if choice.text2 %}
            {{ choice.text2 }}<br />
        {% endif %}
        {% if choice.url2 %}
            <a href="{{ choice.url2 }}">{{ choice.url2 }}</a>
        {% endif %}
    </div>
    <div class="col-md-1"></div>
</div> <!--row-->

<div class="row" id="time_container">
    <div class="col-md-3"></div>
    <div class="col-md-6" id="timer">   
        Time limit: {{ choice.time_limit_str }} minutes<br />
        Time remaining: {{ choice.time_remaining }}
    </div>
    <div class="col-md-3"></div>
</div> <!--row-->
{% endblock %}

{% block footer %}
<p style="text-align: center">Click <a href='/accounts/logout/'>here</a> to logout.</p>
{% endblock %}

templates/choices/view_ultimatum.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load template_library %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "assets/css/view_ultimatum.css" %}"/>
{% endblock %}

{% block title %}
View Choice
{% endblock %}


{% block body_title %}
View Choice
{% endblock %}

{% block content %}
<div class="row" id="question_container">
    {% if message %}{{ message }}<br />{% endif %}
    Question: {{ choice.question }}
</div>
<hr/>

<div class="row" id="option_container">
    <div class="col-md-1"></div>
    <div class="col-md-4" id="option1">
        Option A <br />
        {% if choice.image1 %}
            <img src='/static/assets/{{ choice.image1 }}'/><br />
        {% endif %}
        {% if choice.text1 %}
            {{ choice.text1 }}<br />
        {% endif %}
        {% if choice.url1 %}
            <a href="{{ choice.url1 }}">{{ choice.url1 }}</a>
        {% endif %}
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4" id="option2">
        Option B <br />
        {% if choice.image2 %}
            <img src='/static/assets/{{ choice.image2 }}'/><br />
        {% endif %}
        {% if choice.text2 %}
            {{ choice.text2 }}<br />
        {% endif %}
        {% if choice.url2 %}
            <a href="{{ choice.url2 }}">{{ choice.url2 }}</a>
        {% endif %}
    </div>
    <div class="col-md-1"></div>
</div> <!--row-->

<div class="row" id="time_container">
    <div class="col-md-3"></div>
    <div class="col-md-6" id="timer">
        Time limit: {{ choice.time_limit }} minutes<br />
        Time remaining: {{ choice.time_remaining_str }}<br />
        {% if form %}
            <form id='vote_form' action="/choices/view_ultimatum/{{ choice.pk }}" method="post">{% csrf_token %}
                {{ form.vote.label }}: {{ form.vote }}<br/>
                Comment: {{ form2.content }}<br/><br/>
                <input type='submit' value='submit' id='submit'/>
            </form>
        {% endif %}
    </div>
    <div class="col-md-3"></div>
</div> <!--row-->
{% endblock %}

{% block footer %}
<p style="text-align: center">Click <a href='/accounts/logout/'>here</a> to logout.</p>
{% endblock %}

templates/choices/view_ultimatum_results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load template_library %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "assets/css/view_ultimatum_results.css" %}"/>
{% endblock %}

{% block title %}View Results | Ultimatum{% endblock %}


{% block body_title %}
View Results
{% endblock %}

{% block content %}
<div class="row" id="question_container">
    Voting on this ultimatum question has now closed.<br />
    <h3>Results:</h3>
    <h2>
    {% if votes_1 > votes_2 %}Option A Won!
    {% else %} 
        {% if votes_2 > votes_1 %}Option B Won!
        {% else %}It was a draw!
        {% endif %}
    {% endif %}
    </h2>
    {{ total_votes }} p{{ total_votes|pluralize:"erson,eople" }} voted.<br />
    Votes for A:
    {{ votes_1|default_if_none:"0" }}
    {% if total_votes %}({{ votes_1|percentage:total_votes }}%){% endif %}<br />
    Votes for B: 
    {{ votes_2|default_if_none:"0"}}
    {% if total_votes %}({{ votes_2|percentage:total_votes }}%){% endif %}<br />
    Question: {{ choice.question }}

    {% if form3 %}     
        <form id='accepted_form' action="/choices/view_ultimatum/{{ choice.pk }}" method="post">{% csrf_token %}
            Which option will you go for: {{ form3.accepted }}<br/>
            <input type='submit' value='submit' id='submit'/>
        </form>
    {% endif %}
    {% if choice.accepted %}
        <br />
        {% if choice.created_by == siteuser %}
            You 
        {% else %}
            The owner of this question
        {% endif %}
        decided to go for Option {{ choice.accepted }}.
    {% endif %}
</div>
<hr/>

<div class="row" id="option_container">
    <div class="col-md-1"></div>
     <div class="col-md-4" id="option1">
        Option A <br />
        {% if choice.image1 %}
            <img src='/static/assets/{{ choice.image1 }}'/><br />
        {% endif %}
        {% if choice.text1 %}
            {{ choice.text1 }}<br />
        {% endif %}
        {% if choice.url1 %}
            <a href="{{ choice.url1 }}">{{ choice.url1 }}</a>
        {% endif %}
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4" id="option2">
        Option B <br />
        {% if choice.image2 %}
            <img src='/static/assets/{{ choice.image2 }}'/><br />
        {% endif %}
        {% if choice.text2 %}
            {{ choice.text2 }}<br />
        {% endif %}
        {% if choice.url2 %}
            <a href="{{ choice.url2 }}">{{ choice.url2 }}</a>
        {% endif %}
    </div>
    <div class="col-md-1"></div>
    </div>
</div> <!--row-->
<hr />
<div class="row" id="comments_container">
    <div class="col-md-1"></div>
    <div class="col-md-4 comments">
        <br /><br /><br />
        <h3>Voted for A:</h3> <br/>
        {% if commentsA %}
            {% for comment in commentsA %}
                {{ comment.content }}<br/>
                {{ comment.user | capfirst }}, {{ comment.time_created }}<br/><br/>
            {% endfor %}
        {% else %}
            None
        {% endif %}
    </div>
    <div class="col-md-2 comments">
        <h2 style="text-align: center">Comments</h2>
    </div>
    <div class="col-md-4 comments">
        <br /><br /><br />
        <h3>Voted for B:</h3> <br/>
        {% if commentsB %}
            {% for comment in commentsB %}
                {{ comment.content }}<br/>
                {{ comment.user | capfirst }}, {{ comment.time_created }}<br/><br/>
            {% endfor %}
        {% else %}
            None
        {% endif %}
    </div>
    <div class="col-md-1"></div>
</div> <!--row-->
{% endblock %}

{% block footer %}
<p style="text-align: center">Click <a href='/accounts/logout/'>here</a> to logout.</p>
{% endblock %}

templates/choices/view_ultimatums.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load template_library %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "assets/css/view_ultimatums.css" %}"/>
{% endblock %}

{% block title %}
View Choices
{% endblock %}


{% block body_title %}
View Choices
{% endblock %}

{% block content %}
{% if user_ultimatums %}
<div id="user_created">
    Choices that you have created: <br />
    {% if user_ultimatums %}
        {% for ultimatum in user_ultimatums %}
            <a href="/choices/view_ultimatum/{{ ultimatum.pk }}">{{ ultimatum|truncatechars:40 }} |
            {{ ultimatum.total_votes }} vote{{ ultimatum.total_votes|pluralize:",s" }} | 
            {{ ultimatum.time_created |date:"j F \a\t H:i" }} |
            {% if ultimatum.expired %}
                Voting closed 
                {% if ultimatum not in siteuser.viewed_results.all %}
                    <span class="highlight">*see results!*</span>
                {% endif %}
            {% else %}
                Time remaining: {{ ultimatum.time_remaining_str }}
            {% endif %}</a><br />
        {% endfor %}
    {% else %}
        None
    {% endif %}
</div>
<br />
{% endif %}
{% if other_ultimatums %}
<div id="other_created">
    Choices that others have invited you to vote on:<br />
    {% if other_ultimatums %}
        {% for ultimatum in other_ultimatums %}
            <a href="/choices/view_ultimatum/{{ ultimatum.pk }}">{{ ultimatum|truncatechars:40 }} |
            {{ ultimatum.total_votes }} vote{{ ultimatum.total_votes|pluralize:",s" }} | 
            {{ ultimatum.time_created |date:"j F \a\t H:i" }} |
            {% if ultimatum.expired %}
                Voting closed
                {% if ultimatum not in siteuser.viewed_results.all %}
                    <span class="highlight">*see results!*</span>
                {% endif %}
            {% else %}
                Time remaining: {{ ultimatum.time_remaining_str }}
                {% if ultimatum not in siteuser.viewed_current.all %}
                    <span class="highlight">*New!*</span>
                {% else %}{% if siteuser not in ultimatum.voted_1.all and siteuser not in ultimatum.voted_2.all %}
                    <span class="highlight">*Not yet voted!*</span>
                    {% endif %}
                {% endif %}
            {% endif %}</a><br />
        {% endfor %}
    {% else %}
        None
    {% endif %}
</div>
<br />
<div id="public">
    Choices that the public have invited you to vote on:<br />
    {% if public_ultimatums %}
        {% for ultimatum in public_ultimatums %}
            <a href="/choices/view_ultimatum/{{ ultimatum.pk }}">{{ ultimatum|truncatechars:40 }} |
            {{ ultimatum.total_votes }} vote{{ ultimatum.total_votes|pluralize:",s" }} | 
            {{ ultimatum.time_created |date:"j F \a\t H:i" }} |
            {% if ultimatum.expired %}
                Voting closed
                {% if ultimatum not in siteuser.viewed_results.all %}
                    <span class="highlight">*see results!*</span>
                {% endif %}
            {% else %}
                Time remaining: {{ ultimatum.time_remaining_str }}
                {% if ultimatum not in siteuser.viewed_current.all %}
                    <span class="highlight">*New!*</span>
                {% else %}{% if siteuser not in ultimatum.voted_1.all and siteuser not in ultimatum.voted_2.all %}
                    <span class="highlight">*Not yet voted!*</span>
                    {% endif %}
                {% endif %}
            {% endif %}</a><br />
        {% endfor %}
    {% else %}
        None
    {% endif %}
</div>
{% endif %}
{% endblock %}

{% block footer %}
<p style="text-align: center">Click <a href='/accounts/logout/'>here</a> to logout.</p>
{% endblock %}